// Copyright 2022 MoMA Lab, NYU Abu Dhabi (wp.nyu.edu/momalab/)
#ifndef _E3_MAIN_H_
#define _E3_MAIN_H_

namespace e3
{
namespace cr
{

const char * const LogoF = "# Generated by Circle\n";
const char * const LogoC = "Circle - Circuit Compiler, 2018-2019 MoMA lab, NYU, v0.9.3\n";

}
} // e3::cr

#endif // _E3_MAIN_H_
