import os

# lambdas = ['4'] + [str(l) for l in range(10,101,10)]
lambdas = []
i = 1816 # 1
inc = 8 # 1
while i <= 2048:
    lambdas.append(str(i))
    if 2**(inc+3) <= i:
        inc <<= 1
    i += inc
seeds = [str(s) for s in range(10)]

def main():
    user = 'user/operators/'
    cgt_short = 'cgt_auto.cfg'
    cgt = '{}{}'.format(user, cgt_short)
    time = 10*10**6
    encfile = '{}encrypted.tmp'.format(user)
    decfile_short = 'decrypted.tmp'
    decfile = '{}{}'.format(user, decfile_short)
    timeCSV = 'time_ops.csv'
    # correctCSV = 'correct.csv'
    bdds = ['N-8', 'N-32'] #, 'A', 'AZ', 'F', 'FM']
    operators = ['ADD', 'DIV', 'MUL']
    nbdds = len(bdds)
    nOperators = len(operators)

    if not os.path.isfile(timeCSV):
        items = ['']
        for bdd in bdds:
            items += nOperators * [bdd]
        writeRowCSV(filename=timeCSV, items=items)
        writeRowCSV(filename=timeCSV, items=['lambda'] + nbdds*operators)

    for l in lambdas:
        for seed in seeds:
            writeConfig(cgt_short, l, seed)
            compile(user, cgt)
            run(decfile, time)
            writeRowCSV(timeCSV, [l]+loadTimingResults(decfile_short, nOperators))

def compile(user, cgt):
    # command = 'cd ../.. && make c && rm -rf *key* x.* && make USER={} CGT={} CUDD=1'.format(user, cgt)
    command = 'cd ../.. && rm -rf *.key secint.* && make USER={} CGT={} MPIR=1'.format(user, cgt)
    os.system(command)

def loadTimingResults(filename, nOperators):
    lout = []
    with open(filename, 'r') as fin:
        lines = fin.read().splitlines()
        indexes = [lines.index(l) for l in lines if 'bdd' in l]
        for idx in indexes:
            for g in range(nOperators):
                lout.append( lines[idx+1+g].split(' ')[-1] )
    return lout

def run(filename, time):
    command = 'cd ../.. && ./bob.exe > {} {}'.format(filename, time)
    os.system(command)

def writeConfig(filename, l, seed):
    with open(filename, 'w') as fout:
        cgt = """#generated by testOperators.py
password = hello_world"""+seed+"""

@kernel = bbs
@circuitDB = pil
# @formula = FLF
@sizes = 8,32
@lambda = """+l+"""
@compile = [ unx: g++ $.cpp -o $.exe ][ win: cl -EHsc -Ox -nologo $.cpp ]

BN : circuit
{
	postfix = E
    postneg = En
	encryption = pil
}
        """
        fout.write(cgt)

def writeRowCSV(filename, items):
    with open(filename, 'a') as fout:
        strout = ''
        for item in items:
            strout += item+','
        fout.write('{}\n'.format(strout[:-1]))

if __name__ == '__main__':
    main()
